trigger:
  branches:
    include: 
    - master
variables:
  buildConfiguration: 'Release'
  location: 'West US 2'
  acrHostName: 'ananapi.azurecr.io'
  acrName: 'ananapi'
  rgName: 'registry'
  imageName: 'dockerdemo'
  webAppName: 'capedocker'
  subscription: 'ADOSC'
  regconnect: 'test'

  # webAppNamestg: 'capedockerstg'
  # webAppNameprd: 'capedockerprd'
stages:

# Build Stage
- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'Ubuntu-latest'
    steps:


# # Create or update the ACR resource
#     - task: AzureResourceGroupDeployment@2
#       displayName: 'Azure Deployment:Create Azure Container Registry'
#       inputs:
#         azureSubscription: '$(subscription)'
#         resourceGroupName: '$(rgName)'
#         location: $(location)
#         csmFile: '$(System.DefaultWorkingDirectory)/**/containerRegistry-template.json'
#         overrideParameters: '-registryName "$(acrName)" -registryLocation "$(location)" -registrySku standard'

# Create MySQL Database
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure Container Registry'
      inputs:
        azureSubscription: '$(subscription)'
        resourceGroupName: '$(rgName)'
        location: $(location)
        csmFile: '$(System.DefaultWorkingDirectory)/**/database-webapp-template.json'
        

#Login to ACR
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: test

#Build java Artifact
    - task: Maven@3
      inputs:
        mavenPomFile: 'react-and-spring-data-rest/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package -Dmaven.test.skip=true'

# Build and push image to ACR
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: cape-demo
        tags: latest

 # Copy ARM templates
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        SourceFolder: ArmTemplates
        TargetFolder: '$(build.artifactstagingdirectory)'

    # Publish the app as an artifact
    - publish: $(Build.StagingDirectory)
      artifact: app


# Dev release
- stage: DEV_Stage
  jobs:
  - job: Release
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    # Don't clone the repo
    - checkout: none

    # Download the published application artifact
    - download: current
      artifact: app

    # Create or update Azure App Service
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure App Service'
      inputs:
        azureSubscription: '$(subscription)'
        resourceGroupName: '$(rgName)'
        location: '$(location)'
        csmFile: '$(Pipeline.Workspace)/**/container-webapp-template.json'
        overrideParameters: '-webAppName "$(webAppName)-dev" -hostingPlanName $(webAppName) -appInsightsLocation "$(location)" -sku "S1 Standard" -registryName $(acrName) -registryLocation "$(location)" -registrySku standard -imageName $(imageName):$(Build.BuildId)'

    # Deploy App Service
    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy Azure App Service'
      inputs:
        azureSubscription: '$(subscription)'
        appType: applinux
        WebAppName: "$(webAppName)-dev"
        DockerNamespace: $(acrHostName)
        DockerRepository: $(webAppName)
        DockerImageTag: '$(Build.BuildId)'
        WebAppUri: webAppUrl
        TakeAppOfflineFlag: true
        UseWebDeploy: true
        RenameFilesFlag: true

#Staging release
- stage: STG_Release
  jobs:
  - job: Release
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    # Don't clone the repo
    - checkout: none

    # Download the published application artifact
    - download: current
      artifact: app

    # Create or update Azure App Service
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure App Service'
      inputs:
        azureSubscription: '$(subscription)'
        resourceGroupName: '$(rgName)'
        location: '$(location)'
        csmFile: '$(Pipeline.Workspace)/**/container-webapp-template.json'
        overrideParameters: '-webAppName "$(webAppName)-stg" -hostingPlanName $(webAppName) -appInsightsLocation "$(location)" -sku "S1 Standard" -registryName $(acrName) -registryLocation "$(location)" -registrySku standard -imageName $(imageName):$(Build.BuildId)'

    # Deploy App Service
    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy Azure App Service'
      inputs:
        azureSubscription: '$(subscription)'
        appType: applinux
        WebAppName: "$(webAppName)-stg"
        DockerNamespace: $(acrHostName)
        DockerRepository: $(webAppName)
        DockerImageTag: '$(Build.BuildId)'
        WebAppUri: webAppUrl
        TakeAppOfflineFlag: true
        UseWebDeploy: true
        RenameFilesFlag: true

#PRD release
- stage: PRD_Stage
  jobs:
  - job: Release
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    # Don't clone the repo
    - checkout: none

    # Download the published application artifact
    - download: current
      artifact: app

    # Create or update Azure App Service
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Azure App Service'
      inputs:
        azureSubscription: '$(subscription)'
        resourceGroupName: '$(rgName)'
        location: '$(location)'
        csmFile: '$(Pipeline.Workspace)/**/container-webapp-template.json'
        overrideParameters: '-webAppName "$(webAppName)-prd" -hostingPlanName $(webAppName) -appInsightsLocation "$(location)" -sku "S1 Standard" -registryName $(acrName) -registryLocation "$(location)" -registrySku standard -imageName $(imageName):$(Build.BuildId)'

    # Deploy App Service
    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy Azure App Service'
      inputs:
        azureSubscription: '$(subscription)'
        appType: applinux
        WebAppName: "$(webAppName)-prd"
        DockerNamespace: $(acrHostName)
        DockerRepository: $(webAppName)
        DockerImageTag: '$(Build.BuildId)'
        WebAppUri: webAppUrl
        TakeAppOfflineFlag: true
        UseWebDeploy: true
        RenameFilesFlag: true

#Destroy Function
- stage: DestroyEnvironment
  jobs:
  - deployment: DestroyAll
    environment: 'Destroy'
    strategy:
     runOnce:
       deploy:
         steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: '$(subscription)'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az group delete --name $(rgName) --yes'
              powerShellErrorActionPreference: 'silentlyContinue'
         